CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_key ON users (lower(username));
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key ON users (lower(email));

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS topics (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z][a-z0-9_-]{0,39}$'),
    name text NOT NULL CHECK (btrim(name) <> ''),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS topics_name_lower_key ON topics (lower(name));

DROP TRIGGER IF EXISTS topics_set_updated_at ON topics;
CREATE TRIGGER topics_set_updated_at
BEFORE UPDATE ON topics
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS subtopics (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    slug text NOT NULL CHECK (slug ~ '^[a-z][a-z0-9_-]{0,39}$'),
    name text NOT NULL CHECK (btrim(name) <> ''),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (topic_id, slug)
);

CREATE UNIQUE INDEX IF NOT EXISTS subtopics_topic_name_lower_key
    ON subtopics (topic_id, lower(name));

CREATE UNIQUE INDEX IF NOT EXISTS subtopics_topic_id_id_key
    ON subtopics (topic_id, id);

DROP TRIGGER IF EXISTS subtopics_set_updated_at ON subtopics;
CREATE TRIGGER subtopics_set_updated_at
BEFORE UPDATE ON subtopics
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS learning_documents (
    name text PRIMARY KEY CHECK (name IN ('plan', 'knowledge', 'handoff', 'history', 'patterns')),
    content text NOT NULL,
    sha256 text NOT NULL,
    imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS instructions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text text NOT NULL CHECK (btrim(text) <> ''),
    position integer NOT NULL CHECK (position >= 1),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS instructions_position_key ON instructions (position, id);

DROP TRIGGER IF EXISTS instructions_set_updated_at ON instructions;
CREATE TRIGGER instructions_set_updated_at
BEFORE UPDATE ON instructions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS history_sections (
    position integer PRIMARY KEY,
    heading text NOT NULL,
    body text NOT NULL
);

CREATE TABLE IF NOT EXISTS questions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    subtopic_id bigint NOT NULL,
    text text NOT NULL CHECK (btrim(text) <> ''),
    difficulty smallint NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (topic_id, subtopic_id) REFERENCES subtopics(topic_id, id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS questions_subtopic_text_lower_key
    ON questions (subtopic_id, lower(text));

CREATE INDEX IF NOT EXISTS questions_active_lookup
    ON questions (topic_id, subtopic_id, difficulty, id) WHERE is_active = true;

DROP TRIGGER IF EXISTS questions_set_updated_at ON questions;
CREATE TRIGGER questions_set_updated_at
BEFORE UPDATE ON questions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS answers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id),
    topic_id bigint NOT NULL REFERENCES topics(id),
    subtopic_id bigint REFERENCES subtopics(id) ON DELETE SET NULL,
    question_id integer REFERENCES questions(id) ON DELETE SET NULL,
    score smallint NOT NULL CHECK (score BETWEEN 0 AND 5),
    difficulty smallint NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
    independence_score smallint NOT NULL CHECK (independence_score BETWEEN 1 AND 5),
    clarity_score smallint NOT NULL CHECK (clarity_score BETWEEN 1 AND 5),
    completeness_score smallint NOT NULL CHECK (completeness_score BETWEEN 1 AND 5),
    confidence_score smallint NOT NULL CHECK (confidence_score BETWEEN 1 AND 5),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (subtopic_id IS NULL OR topic_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS answers_user_topic_recent
    ON answers (user_id, topic_id, subtopic_id, created_at DESC, id DESC);

DROP TRIGGER IF EXISTS answers_set_updated_at ON answers;
CREATE TRIGGER answers_set_updated_at
BEFORE UPDATE ON answers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS learning_state (
    user_id integer PRIMARY KEY REFERENCES users(id),
    next_topic_id bigint REFERENCES topics(id),
    next_question text,
    updated_at timestamptz NOT NULL DEFAULT now()
);
