"""Migrate the legacy learning_policy blob into ordered instructions."""

import re

import psycopg


DEFAULT_INSTRUCTIONS = [
    "Обучение за Python/Data Engineering Team Lead на български.",
    "Без код по подразбиране.",
    "Задавай по един кратък сценарий за архитектурна преценка, trade-offs, диагностика, коректност, производителност или design review.",
    "Всички технологии са равнопоставени.",
    "Редувай темите и не повтаряй наскоро проверени сценарии.",
    "Дай възможност за самостоятелен отговор преди подсказки.",
    "След отговора отдели показаното самостоятелно от изясненото с помощ и от непровереното.",
    "Прочетено обяснение не доказва усвоено знание.",
    "Не следи учебно време.",
]


def split_legacy_instructions(text):
    if not text or not text.strip():
        return DEFAULT_INSTRUCTIONS
    parts = [part.strip() for part in re.split(r"(?<=\.)\s+", text.strip()) if part.strip()]
    return parts or DEFAULT_INSTRUCTIONS


def migrate(conn):
    conn.execute("SET ROLE learnikal")
    legacy = conn.execute("SELECT to_regclass('public.learning_policy')").fetchone()[0]
    legacy_text = None
    if legacy:
        row = conn.execute("SELECT instructions FROM learning_policy WHERE id = true").fetchone()
        legacy_text = row[0] if row else None

    conn.execute(
        """CREATE TABLE IF NOT EXISTS instructions (
               id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               text text NOT NULL CHECK (btrim(text) <> ''),
               position integer NOT NULL CHECK (position >= 1),
               is_active boolean NOT NULL DEFAULT true,
               created_at timestamptz NOT NULL DEFAULT now(),
               updated_at timestamptz NOT NULL DEFAULT now()
           )"""
    )
    conn.execute("CREATE INDEX IF NOT EXISTS instructions_position_key ON instructions (position, id)")
    conn.execute(
        """CREATE OR REPLACE FUNCTION set_updated_at()
           RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
               NEW.updated_at = now();
               RETURN NEW;
           END;
           $$"""
    )
    conn.execute("DROP TRIGGER IF EXISTS instructions_set_updated_at ON instructions")
    conn.execute(
        """CREATE TRIGGER instructions_set_updated_at BEFORE UPDATE ON instructions
           FOR EACH ROW EXECUTE FUNCTION set_updated_at()"""
    )

    existing_count = conn.execute("SELECT COUNT(*) FROM instructions").fetchone()[0]
    if existing_count == 0:
        for position, text in enumerate(split_legacy_instructions(legacy_text), start=1):
            conn.execute(
                "INSERT INTO instructions (text, position) VALUES (%s, %s)",
                (text, position),
            )

    active_count = conn.execute("SELECT COUNT(*) FROM instructions WHERE is_active = true").fetchone()[0]
    if active_count == 0:
        raise ValueError("At least one active instruction is required")
    if legacy:
        conn.execute("DROP TABLE learning_policy")
    return conn.execute("SELECT COUNT(*) FROM instructions").fetchone()[0]


def main():
    with psycopg.connect("dbname=learnikal user=postgres") as conn:
        count = migrate(conn)
    print(f"Verified instructions table: {count} instruction(s)")


if __name__ == "__main__":
    main()
