"""Migrate learning rules and documents into typed instructions."""

import csv
from pathlib import Path

import psycopg


IMPORT_FILE = Path(__file__).with_name("learning-documents-to-instructions-import.csv")
DOCUMENT_TYPES = {
    "plan": "plan",
    "knowledge": "knowledge",
    "handoff": "handoff",
    "history": "history",
    "patterns": "patterns",
}
ALLOWED_TYPES = ("behavior", *DOCUMENT_TYPES.values())


def read_behavior_instructions():
    with IMPORT_FILE.open(encoding="utf-8-sig", newline="") as source:
        rows = list(csv.DictReader(source))
    if not rows or set(rows[0]) != {"position", "text"}:
        raise ValueError(f"Unexpected instruction import format: {IMPORT_FILE}")
    parsed = [(int(row["position"]), row["text"].strip()) for row in rows]
    if [position for position, _text in parsed] != list(range(1, len(parsed) + 1)):
        raise ValueError("Behavior instruction positions must start at 1 and be contiguous")
    if any(not text for _position, text in parsed):
        raise ValueError("Behavior instruction text cannot be blank")
    return parsed


def migrate_documents(conn):
    if conn.execute("SELECT to_regclass('public.learning_documents')").fetchone()[0] is None:
        return 0

    documents = conn.execute(
        "SELECT name, content FROM learning_documents ORDER BY name"
    ).fetchall()
    for document in documents:
        instruction_type = DOCUMENT_TYPES.get(document[0])
        if instruction_type is None:
            raise ValueError(f"Unknown learning document type: {document[0]}")
        rows = conn.execute(
            'SELECT id FROM instructions WHERE "type" = %s ORDER BY position, id',
            (instruction_type,),
        ).fetchall()
        if rows:
            instruction_id = rows[0][0]
            conn.execute(
                '''UPDATE instructions SET text = %s, position = 1, is_active = true
                   WHERE id = %s''',
                (document[1], instruction_id),
            )
            conn.execute(
                '''UPDATE instructions SET is_active = false
                   WHERE "type" = %s AND id <> %s''',
                (instruction_type, instruction_id),
            )
        else:
            conn.execute(
                '''INSERT INTO instructions ("type", text, position, is_active)
                   VALUES (%s, %s, 1, true)''',
                (instruction_type, document[1]),
            )

    imported_types = {
        row[0]
        for row in conn.execute(
            'SELECT DISTINCT "type" FROM instructions WHERE "type" <> \'behavior\' AND is_active = true'
        ).fetchall()
    }
    expected_types = {DOCUMENT_TYPES[row[0]] for row in documents}
    if expected_types != set(DOCUMENT_TYPES.values()):
        missing = sorted(set(DOCUMENT_TYPES.values()) - expected_types)
        raise ValueError("Missing learning documents: " + ", ".join(missing))
    if not expected_types.issubset(imported_types):
        raise ValueError("Learning documents were not migrated into typed instructions")
    return len(documents)


def migrate(conn):
    conn.execute("SET ROLE learnikal")
    legacy = conn.execute("SELECT to_regclass('public.learning_policy')").fetchone()[0]

    conn.execute(
        '''CREATE TABLE IF NOT EXISTS instructions (
               id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               "type" text NOT NULL DEFAULT 'behavior',
               text text NOT NULL CHECK (btrim(text) <> ''),
               position integer NOT NULL CHECK (position >= 1),
               is_active boolean NOT NULL DEFAULT true,
               created_at timestamptz NOT NULL DEFAULT now(),
               updated_at timestamptz NOT NULL DEFAULT now()
           )'''
    )
    conn.execute(
        '''ALTER TABLE instructions ADD COLUMN IF NOT EXISTS "type" text NOT NULL DEFAULT 'behavior' '''
    )
    has_type_check = conn.execute(
        "SELECT 1 FROM pg_constraint WHERE conrelid = 'public.instructions'::regclass "
        "AND conname = 'instructions_type_check'"
    ).fetchone()
    if not has_type_check:
        allowed = ", ".join("'" + value + "'" for value in ALLOWED_TYPES)
        conn.execute(
            f'ALTER TABLE instructions ADD CONSTRAINT instructions_type_check CHECK ("type" IN ({allowed}))'
        )
    conn.execute(
        'CREATE INDEX IF NOT EXISTS instructions_type_position_key ON instructions ("type", position, id)'
    )
    conn.execute(
        '''CREATE OR REPLACE FUNCTION set_updated_at()
           RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
               NEW.updated_at = now();
               RETURN NEW;
           END;
           $$'''
    )
    conn.execute("DROP TRIGGER IF EXISTS instructions_set_updated_at ON instructions")
    conn.execute(
        '''CREATE TRIGGER instructions_set_updated_at BEFORE UPDATE ON instructions
           FOR EACH ROW EXECUTE FUNCTION set_updated_at()'''
    )

    behavior = read_behavior_instructions()
    current = conn.execute(
        'SELECT id FROM instructions WHERE "type" = \'behavior\' ORDER BY position, id'
    ).fetchall()
    for index, (position, text) in enumerate(behavior):
        if index < len(current):
            conn.execute(
                '''UPDATE instructions SET text = %s, position = %s, is_active = true
                   WHERE id = %s''',
                (text, position, current[index][0]),
            )
        else:
            conn.execute(
                '''INSERT INTO instructions ("type", text, position, is_active)
                   VALUES ('behavior', %s, %s, true)''',
                (text, position),
            )
    for row in current[len(behavior):]:
        conn.execute("UPDATE instructions SET is_active = false WHERE id = %s", (row[0],))

    document_count = migrate_documents(conn)
    active_behavior_count = conn.execute(
        'SELECT COUNT(*) FROM instructions WHERE "type" = \'behavior\' AND is_active = true'
    ).fetchone()[0]
    if active_behavior_count != len(behavior):
        raise ValueError("Behavior instruction migration did not verify")
    if legacy:
        conn.execute("DROP TABLE learning_policy")
    total = conn.execute("SELECT COUNT(*) FROM instructions").fetchone()[0]
    return total, active_behavior_count, document_count


def main():
    with psycopg.connect("dbname=learnikal user=postgres") as conn:
        counts = migrate(conn)
    print(
        "Verified typed instructions: "
        f"{counts[0]} total, {counts[1]} behavior rules, {counts[2]} migrated documents"
    )


if __name__ == "__main__":
    main()
