"""Create the LearniKal question bank table and link answers to it."""

import os

import psycopg


DSN = os.getenv("LEARNIKAL_DATABASE_URL", "dbname=learnikal user=postgres")


def constraint_exists(conn, name: str) -> bool:
    return conn.execute("SELECT 1 FROM pg_constraint WHERE conname = %s", (name,)).fetchone() is not None


def column_exists(conn, table: str, column: str) -> bool:
    return conn.execute(
        """SELECT 1 FROM information_schema.columns
           WHERE table_schema = 'public' AND table_name = %s AND column_name = %s""",
        (table, column),
    ).fetchone() is not None


def main() -> None:
    with psycopg.connect(DSN) as conn:
        conn.execute("SET ROLE learnikal")
        conn.execute(
            """CREATE OR REPLACE FUNCTION set_updated_at()
               RETURNS trigger LANGUAGE plpgsql AS $$
               BEGIN
                   NEW.updated_at = now();
                   RETURN NEW;
               END;
               $$"""
        )
        conn.execute(
            """CREATE UNIQUE INDEX IF NOT EXISTS subtopics_topic_id_id_key
               ON subtopics (topic_id, id)"""
        )
        conn.execute(
            """CREATE TABLE IF NOT EXISTS questions (
                   id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                   topic_id bigint NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
                   subtopic_id bigint NOT NULL,
                   text text NOT NULL CHECK (btrim(text) <> ''),
                   difficulty smallint NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
                   is_active boolean NOT NULL DEFAULT true,
                   created_at timestamptz NOT NULL DEFAULT now(),
                   updated_at timestamptz NOT NULL DEFAULT now(),
                   FOREIGN KEY (topic_id, subtopic_id)
                       REFERENCES subtopics(topic_id, id) ON DELETE CASCADE
               )"""
        )
        conn.execute(
            """CREATE UNIQUE INDEX IF NOT EXISTS questions_subtopic_text_lower_key
               ON questions (subtopic_id, lower(text))"""
        )
        conn.execute(
            """CREATE INDEX IF NOT EXISTS questions_active_lookup
               ON questions (topic_id, subtopic_id, difficulty, id) WHERE is_active = true"""
        )
        conn.execute("DROP TRIGGER IF EXISTS questions_set_updated_at ON questions")
        conn.execute(
            """CREATE TRIGGER questions_set_updated_at
               BEFORE UPDATE ON questions
               FOR EACH ROW EXECUTE FUNCTION set_updated_at()"""
        )

        if column_exists(conn, "answers", "question_id"):
            conn.execute(
                """UPDATE answers SET question_id = NULL
                   WHERE question_id IS NOT NULL
                     AND NOT EXISTS (SELECT 1 FROM questions WHERE questions.id = answers.question_id)"""
            )
            if not constraint_exists(conn, "answers_question_id_fkey"):
                conn.execute(
                    """ALTER TABLE answers
                       ADD CONSTRAINT answers_question_id_fkey
                       FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE SET NULL"""
                )

        count = conn.execute("SELECT COUNT(*) FROM questions").fetchone()[0]
    print(f"Verified questions table: {count} question(s)")


if __name__ == "__main__":
    main()
