import os

import psycopg


DSN = os.getenv("LEARNIKAL_DATABASE_URL", "dbname=learnikal user=postgres")


def table_exists(conn, name: str) -> bool:
    row = conn.execute("SELECT to_regclass(%s) AS table_name", (f"public.{name}",)).fetchone()
    return row[0] is not None


def column_exists(conn, table: str, column: str) -> bool:
    row = conn.execute(
        """SELECT 1 FROM information_schema.columns
           WHERE table_schema = 'public' AND table_name = %s AND column_name = %s""",
        (table, column),
    ).fetchone()
    return row is not None


def column_type(conn, table: str, column: str) -> str | None:
    row = conn.execute(
        """SELECT data_type FROM information_schema.columns
           WHERE table_schema = 'public' AND table_name = %s AND column_name = %s""",
        (table, column),
    ).fetchone()
    return row[0] if row else None


def ensure_constraint(conn, name: str, ddl: str) -> None:
    exists = conn.execute(
        "SELECT 1 FROM pg_constraint WHERE conname = %s",
        (name,),
    ).fetchone()
    if exists is None:
        conn.execute(ddl)


def main() -> None:
    with psycopg.connect(DSN) as conn:
        conn.execute("SET ROLE learnikal")
        conn.execute(
            """CREATE OR REPLACE FUNCTION set_updated_at()
               RETURNS trigger LANGUAGE plpgsql AS $$
               BEGIN
                   NEW.updated_at = now();
                   RETURN NEW;
               END;
               $$"""
        )

        if not table_exists(conn, "answers") and table_exists(conn, "learning_entries"):
            conn.execute("ALTER TABLE learning_entries RENAME TO answers")

        conn.execute(
            """DO $$
               BEGIN
                   IF to_regclass('public.learning_entries_id_seq') IS NOT NULL
                      AND to_regclass('public.answers_id_seq') IS NULL THEN
                       ALTER SEQUENCE learning_entries_id_seq RENAME TO answers_id_seq;
                   END IF;
               END $$"""
        )

        conn.execute(
            """CREATE TABLE IF NOT EXISTS answers (
                   id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                   user_id integer NOT NULL REFERENCES users(id),
                   topic_id bigint NOT NULL REFERENCES topics(id),
                   subtopic_id bigint REFERENCES subtopics(id) ON DELETE SET NULL,
                   question_id integer CHECK (question_id > 0),
                   score smallint NOT NULL CHECK (score BETWEEN 0 AND 5),
                   difficulty smallint NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
                   independence_score smallint NOT NULL CHECK (independence_score BETWEEN 1 AND 5),
                   clarity_score smallint NOT NULL CHECK (clarity_score BETWEEN 1 AND 5),
                   completeness_score smallint NOT NULL CHECK (completeness_score BETWEEN 1 AND 5),
                   confidence_score smallint NOT NULL CHECK (confidence_score BETWEEN 1 AND 5),
                   created_at timestamptz NOT NULL DEFAULT now(),
                   updated_at timestamptz NOT NULL DEFAULT now()
               )"""
        )

        if table_exists(conn, "answers"):
            conn.execute("LOCK TABLE answers IN ACCESS EXCLUSIVE MODE")

        conn.execute(
            """DO $$
               BEGIN
                   IF EXISTS (
                       SELECT 1 FROM pg_constraint
                       WHERE conrelid = 'public.answers'::regclass
                         AND conname = 'learning_entries_pkey'
                   ) THEN
                       ALTER TABLE answers RENAME CONSTRAINT learning_entries_pkey TO answers_pkey;
                   END IF;
               END $$"""
        )
        if conn.execute("SELECT to_regclass('public.answers_id_seq')").fetchone()[0] is not None:
            conn.execute("ALTER SEQUENCE answers_id_seq OWNED BY answers.id")
            conn.execute("ALTER TABLE answers ALTER COLUMN id SET DEFAULT nextval('answers_id_seq'::regclass)")

        for ddl in [
            "ALTER TABLE answers ADD COLUMN IF NOT EXISTS subtopic_id bigint",
            "ALTER TABLE answers ADD COLUMN IF NOT EXISTS question_id integer",
            "ALTER TABLE answers ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()",
            "ALTER TABLE answers ADD COLUMN IF NOT EXISTS score smallint",
            "ALTER TABLE answers ADD COLUMN IF NOT EXISTS independence_score smallint",
            "ALTER TABLE answers ADD COLUMN IF NOT EXISTS clarity_score smallint",
            "ALTER TABLE answers ADD COLUMN IF NOT EXISTS completeness_score smallint",
            "ALTER TABLE answers ADD COLUMN IF NOT EXISTS confidence_score smallint",
        ]:
            conn.execute(ddl)

        if column_type(conn, "answers", "difficulty") in {"text", "character varying"}:
            conn.execute("ALTER TABLE answers ADD COLUMN IF NOT EXISTS difficulty_value smallint")
            conn.execute(
                """UPDATE answers SET difficulty_value = CASE difficulty
                       WHEN 'low' THEN 1
                       WHEN 'medium' THEN 3
                       WHEN 'high' THEN 5
                       ELSE 3
                   END
                   WHERE difficulty_value IS NULL"""
            )
            conn.execute("ALTER TABLE answers DROP COLUMN difficulty")
            conn.execute("ALTER TABLE answers RENAME COLUMN difficulty_value TO difficulty")
        elif not column_exists(conn, "answers", "difficulty"):
            conn.execute("ALTER TABLE answers ADD COLUMN difficulty smallint")
        elif column_type(conn, "answers", "difficulty") not in {"smallint", "integer"}:
            conn.execute("ALTER TABLE answers ALTER COLUMN difficulty TYPE smallint USING difficulty::smallint")

        conn.execute("UPDATE answers SET score = COALESCE(score, 0)")
        conn.execute("UPDATE answers SET difficulty = COALESCE(difficulty, 3)")
        conn.execute(
            """UPDATE answers SET
                   independence_score = COALESCE(independence_score, GREATEST(1, LEAST(5, NULLIF(score, 0)))),
                   clarity_score = COALESCE(clarity_score, GREATEST(1, LEAST(5, NULLIF(score, 0)))),
                   completeness_score = COALESCE(completeness_score, GREATEST(1, LEAST(5, NULLIF(score, 0)))),
                   confidence_score = COALESCE(confidence_score, GREATEST(1, LEAST(5, NULLIF(score, 0))))"""
        )
        conn.execute(
            """UPDATE answers SET
                   independence_score = COALESCE(independence_score, 3),
                   clarity_score = COALESCE(clarity_score, 3),
                   completeness_score = COALESCE(completeness_score, 3),
                   confidence_score = COALESCE(confidence_score, 3)"""
        )
        conn.execute("UPDATE answers SET updated_at = COALESCE(updated_at, created_at, now())")

        for column in ["score", "difficulty", "independence_score", "clarity_score", "completeness_score", "confidence_score", "updated_at"]:
            conn.execute(f"ALTER TABLE answers ALTER COLUMN {column} SET NOT NULL")

        for column in ["question", "answer", "evaluation", "next_question"]:
            if column_exists(conn, "answers", column):
                conn.execute(f"ALTER TABLE answers DROP COLUMN {column}")

        ensure_constraint(conn, "answers_question_id_check", "ALTER TABLE answers ADD CONSTRAINT answers_question_id_check CHECK (question_id > 0)")
        ensure_constraint(conn, "answers_score_check", "ALTER TABLE answers ADD CONSTRAINT answers_score_check CHECK (score BETWEEN 0 AND 5)")
        ensure_constraint(conn, "answers_difficulty_check", "ALTER TABLE answers ADD CONSTRAINT answers_difficulty_check CHECK (difficulty BETWEEN 1 AND 5)")
        ensure_constraint(conn, "answers_independence_score_check", "ALTER TABLE answers ADD CONSTRAINT answers_independence_score_check CHECK (independence_score BETWEEN 1 AND 5)")
        ensure_constraint(conn, "answers_clarity_score_check", "ALTER TABLE answers ADD CONSTRAINT answers_clarity_score_check CHECK (clarity_score BETWEEN 1 AND 5)")
        ensure_constraint(conn, "answers_completeness_score_check", "ALTER TABLE answers ADD CONSTRAINT answers_completeness_score_check CHECK (completeness_score BETWEEN 1 AND 5)")
        ensure_constraint(conn, "answers_confidence_score_check", "ALTER TABLE answers ADD CONSTRAINT answers_confidence_score_check CHECK (confidence_score BETWEEN 1 AND 5)")
        ensure_constraint(conn, "answers_subtopic_id_fkey", "ALTER TABLE answers ADD CONSTRAINT answers_subtopic_id_fkey FOREIGN KEY (subtopic_id) REFERENCES subtopics(id) ON DELETE SET NULL")

        conn.execute("DROP INDEX IF EXISTS learning_entries_user_topic_recent")
        conn.execute(
            """CREATE INDEX IF NOT EXISTS answers_user_topic_recent
               ON answers (user_id, topic_id, subtopic_id, created_at DESC, id DESC)"""
        )
        conn.execute("DROP TRIGGER IF EXISTS answers_set_updated_at ON answers")
        conn.execute(
            """CREATE TRIGGER answers_set_updated_at
               BEFORE UPDATE ON answers
               FOR EACH ROW EXECUTE FUNCTION set_updated_at()"""
        )
        conn.execute(
            """COMMENT ON COLUMN answers.question_id IS
               'Will reference questions(id) after the questions table is introduced.'"""
        )

        if table_exists(conn, "learning_entries"):
            raise RuntimeError("learning_entries still exists after answers migration")


if __name__ == "__main__":
    main()
